name: EternalClaims
main: xyz.oribuin.eternalclaims.EternalClaims
version: '@version@'
api-version: 1.17
author: Oribuin
description: oh boy another claims plugin
softdepend:
  - Vault
  - PlaceholderAPI
  - WorldGuard
  - PlayerPoints
