name: EternalClaims
main: dev.oribuin.eternalclaims.EternalClaims
version: '${version}'
api-version: 1.21
author: Oribuin
description: oh boy another claims plugin
softdepend:
  - Vault
  - PlaceholderAPI
